apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/aidana0804/Argocd_kubernetes_programmer_ayimdar_final.git
    path: argocd-apps/alertmanager  # Path to the directory where the Alertmanager chart is located
    targetRevision: HEAD
    helm:
      valueFiles:
        - alermanaget-values.yaml  # Reference to the values.yaml for Alertmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
