apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: hostname
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret.name }}
                  key: database
          ports:
            - containerPort: {{ .Values.service.backend.containerPort }}
