apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalDns.google.serviceAccountSecretName}}
  namespace: default 
type: Opaque
data:
  credentials.json: {{ .Files.Get "kubernetes-434707-535ba2c356b5.json" | b64enc }}
