apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecret.name }}
type: Opaque
data:
  database: {{ .Values.dbSecret.database }}
  hostname: {{ .Values.dbSecret.hostname }}
  password: {{ .Values.dbSecret.password }}
  username: {{ .Values.dbSecret.username }}
