apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.servicePort }}
      targetPort: {{ .Values.service.frontend.containerPort }}
  type: ClusterIP
